# WandB hyperparameter sweep configuration file

program: src/ml_ops/train.py
method: random # random/grid/bayes
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
name: sweepdemo
project: corrupt_mnist_sweep
entity: schependom-ku-leuven
metric:
    goal: minimize
    name: validation_loss
parameters:
    optimizer.lr:
        min: 0.0001
        max: 0.1
        distribution: log_uniform_values
    batch_size:
        values: [16, 64]
    epochs:
        values: [5, 15]
run_cap: 10
