name: Unit Tests

on:
  push:
    branches: # all
      
  pull_request:
    branches: # all

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Now uses uv for dependency management
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      # Download dvc data
      - uses: iterative/setup-dvc@v2

      - name: Pull DVC data
        shell: bash
        env:
          SSH_KEY: ${{ secrets.DVC_SSH_KEY }}
          DVC_SSH_PASSPHRASE: ${{ secrets.DVC_SSH_PASSPHRASE }}
          SSH_PASS: ${{ secrets.DTU_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          
          # Write the SSH key to the Ed25519 file
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Remove the passphrase from the new key file
          ssh-keygen -p -f ~/.ssh/id_ed25519 -P "$DVC_SSH_PASSPHRASE" -N ""

          ssh-keyscan -H ${{ secrets.DVC_SSH_HOSTNAME }} >> ~/.ssh/known_hosts

          echo "Host gbar1" >> ~/.ssh/config
          echo "  HostName ${{ secrets.DVC_SSH_HOSTNAME }}" >> ~/.ssh/config
          echo "  User ${{ secrets.DVC_SSH_USERNAME }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config

          # Check if sshpass is installed before attempting installation
          if ! command -v sshpass &> /dev/null; then
            echo "sshpass not found, installing..."
            if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install -y sshpass
            elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install sshpass
            elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install sshpass
            fi
          else
            echo "sshpass is already installed."
          fi

          uv run sshpass -p "$SSH_PASS" dvc pull

      - name: Run tests & coverage
        run: |
          uv run coverage run -m pytest tests/
          uv run coverage report -m