name: Unit Tests

on:
  push:
    branches: # all
      
  pull_request:
    branches: # all

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # Use a consistent shell for cross-platform compatibility
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    defaults:
      run:
        shell: bash # Force bash to ensure commands run consistently on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - uses: iterative/setup-dvc@v2

      - name: Configure DVC Credentials
        env:
          SSH_KEY: ${{ secrets.DVC_SSH_KEY }}
          DVC_SSH_PASSPHRASE: ${{ secrets.DVC_SSH_PASSPHRASE }}
          SSH_PASS: ${{ secrets.DTU_PASSWORD }}
          REMOTE_NAME: "hpc_storage" # .dvc/config remote name
        run: |
          # 1. Write the key to a local file in the workspace
          echo "$SSH_KEY" > dvc_key_file

          # 2. Decrypt the key (Remove passphrase)
          if [ -n "$DVC_SSH_PASSPHRASE" ]; then
             # -f: filename, -p: old passphrase, -N: new passphrase (empty)
             ssh-keygen -p -f dvc_key_file -P "$DVC_SSH_PASSPHRASE" -N ""
          fi
          
          # 3. Configure DVC Locally (Does not affect git tracking)
          # This injects the credentials directly into DVC's runtime config
          dvc remote modify --local $REMOTE_NAME user ${{ secrets.DVC_SSH_USERNAME }}
          dvc remote modify --local $REMOTE_NAME keyfile "$(pwd)/dvc_key_file"
          dvc remote modify --local $REMOTE_NAME password "$SSH_PASS"
          
          # Optional: If you need to force a specific port or host alias
          # dvc remote modify --local $REMOTE_NAME port 22

      - name: Pull DVC data
        run: uv run dvc pull